/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching';
import { getNotificationsFromIndexedDB, removeNotificationFromIndexedDB } from './lib/offlineQueue';

declare const self: ServiceWorkerGlobalScope;

// Precache list generated by build
precacheAndRoute(self.__WB_MANIFEST || []);

// Force immediate activation and client control
self.addEventListener('install', () => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    Promise.all([
      self.clients.claim(),
      // Try to sync any remaining offline notifications on SW activation
      syncOfflineNotificationsInServiceWorker().catch((err) => {
        console.error('[Service Worker] Erro na sincronização durante ativação:', err);
      })
    ])
  );
});

// Listen for push notifications from backend (even if app is closed!)
self.addEventListener('push', (event) => {
  console.log('[Service Worker] Evento "push" recebido!', event);

  let data = { title: 'Pátio', body: '' };
  try {
    if (event.data) {
      data = event.data.json();
      console.log('[Service Worker] Payload JSON recebido e decodificado com sucesso:', data);
    } else {
      console.warn('[Service Worker] Evento push sem dados de payload.');
    }
  } catch (err) {
    const textData = event.data ? event.data.text() : '';
    data = { title: 'Pátio', body: textData };
    console.warn('[Service Worker] Erro ao decodificar payload JSON (usando texto puro):', err, 'Texto:', textData);
  }

  const options = {
    body: data.body,
    icon: 'https://i.postimg.cc/SKcgQrKX/openart-image-CVX2wu-Ks-1775830140914-raw-Photoroom.png',
    badge: 'https://i.postimg.cc/SKcgQrKX/openart-image-CVX2wu-Ks-1775830140914-raw-Photoroom.png',
    vibrate: [200, 100, 200],
    data: '/',
  };

  console.log('[Service Worker] Chamando showNotification com Título:', data.title, 'e Opções:', options);

  event.waitUntil(
    self.registration.showNotification(data.title, options)
      .then(() => {
        console.log('[Service Worker] showNotification exibido com sucesso para o usuário!');
      })
      .catch((err) => {
        console.error('[Service Worker] Erro ao disparar showNotification:', err);
      })
  );
});

// Click action - focus or open the app
self.addEventListener('notificationclick', (event) => {
  console.log('[Service Worker] Evento "notificationclick" acionado pelo usuário!', event);
  event.notification.close();
  console.log('[Service Worker] Notificação fechada via notification.close()');

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      console.log(`[Service Worker] Clientes de janela encontrados ativos: ${clientList.length}`);
      for (const client of clientList) {
        if ('focus' in client) {
          console.log('[Service Worker] Focando em janela ativa existente...');
          return client.focus();
        }
      }
      if (self.clients.openWindow) {
        console.log('[Service Worker] Nenhuma janela ativa focável. Abrindo nova janela do app...');
        return self.clients.openWindow('/');
      }
    }).catch((err) => {
      console.error('[Service Worker] Erro ao processar click da notificação:', err);
    })
  );
});

// Background Sync Listener for offline push notifications
self.addEventListener('sync', (event: any) => {
  if (event.tag === 'sync-push-notifications') {
    console.log('[Service Worker] Evento sync "sync-push-notifications" disparado pelo navegador!');
    event.waitUntil(syncOfflineNotificationsInServiceWorker());
  }
});

async function syncOfflineNotificationsInServiceWorker() {
  try {
    const queue = await getNotificationsFromIndexedDB();
    if (queue.length === 0) {
      console.log('[Service Worker Sync] Fila vazia, nada para sincronizar.');
      return;
    }

    console.log(`[Service Worker Sync] Sincronizando ${queue.length} notificações pendentes em plano de fundo...`);

    for (const item of queue) {
      try {
        const targetUrl = `${self.location.origin}/api/notifications/notify-all`;
        
        console.log(`[Service Worker Sync] Tentando enviar notificação pendente: "${item.title}"`);
        const res = await fetch(targetUrl, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            title: item.title,
            body: item.body,
            originDeviceId: item.originDeviceId,
            originUserEmail: item.originUserEmail
          })
        });

        if (res.ok) {
          console.log(`[Service Worker Sync] Notificação pendente enviada com sucesso em background: "${item.title}"`);
          await removeNotificationFromIndexedDB(item.id);
        } else {
          console.warn(`[Service Worker Sync] Falha ao enviar em background: "${item.title}" (Status HTTP: ${res.status}). Mantendo na fila.`);
        }
      } catch (err) {
        console.error(`[Service Worker Sync] Erro de conexão ao enviar em background: "${item.title}". Mantendo na fila.`, err);
      }
    }
  } catch (err) {
    console.error('[Service Worker Sync] Falha geral ao carregar notificações do IndexedDB:', err);
  }
}
