/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching';

declare const self: ServiceWorkerGlobalScope;

// Precache list generated by build
precacheAndRoute(self.__WB_MANIFEST || []);

// Listen for push notifications from backend (even if app is closed!)
self.addEventListener('push', (event) => {
  let data = { title: 'Pátio', body: '' };
  try {
    if (event.data) {
      data = event.data.json();
    }
  } catch (err) {
    data = { title: 'Pátio', body: event.data ? event.data.text() : '' };
  }

  const options = {
    body: data.body,
    icon: 'https://i.postimg.cc/SKcgQrKX/openart-image-CVX2wu-Ks-1775830140914-raw-Photoroom.png',
    badge: 'https://i.postimg.cc/SKcgQrKX/openart-image-CVX2wu-Ks-1775830140914-raw-Photoroom.png',
    vibrate: [200, 100, 200],
    data: '/',
  };

  event.waitUntil(
    self.registration.showNotification(data.title, options)
  );
});

// Click action - focus or open the app
self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      for (const client of clientList) {
        if ('focus' in client) {
          return client.focus();
        }
      }
      if (self.clients.openWindow) {
        return self.clients.openWindow('/');
      }
    })
  );
});
